spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        hbm2dll:
          create_namespaces: true
        default_schema: pager
        ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false